### ISSUE TITLE
LazyNFT new contract deployed for every token minted?

### ISSUE THREAD

**Issue by Gatts011** [ipfs-shipyard/nft-school-examples#8]
Does a new contract need to be deployed for every token? 
If so, how do we get totalSupply across all deployed contracts
If so, wouldn't it be simpler to mint and transfer?

thanks

**Comment by Gatts011** [comment]
Please, any advice would be highly appreciated

**Comment by franleplant** [comment]
No, one contract equals many tokens. NFTs are typically represented as `${tokenContractAddress} ${tokenId}`, you decide whether you want to use a single contract for multiple "nft collections" or one contract for each collection.

AFAIK it is usually handled as one collection one contract, it also gives you more finer control since contracts are inmutable naturally

**Comment by franleplant** [comment]
I would say this is not an issue with this repo, it is more  like an Stack overflow questions

**Comment by Gatts011** [comment]
Thank you for the clarifying @franleplant! I'll redirect my questions to SO from now on.
